
/**************************************************************
 *	
 *	chainSFX, 8 bit, 11025Hz,
 *	1 channel, 12645 bytes/channel
 *	Total Size: 1 * 12645 + 4 (header) = 12689 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\cs2261\M4\chainSFX.wav
 *	Time-stamp: Wed Apr 11 21:05:06 2018
 *	
 **************************************************************/

#ifndef __CHAINSFXH__
#define __CHAINSFXH__

#define CHAINSFXFREQ 11025
#define CHAINSFXLEN 12645

extern const unsigned char chainSFX[12645];

#endif /* __CHAINSFXH__ */
