
/**************************************************************
 *	
 *	end, 8 bit, 11025Hz,
 *	1 channel, 247287 bytes/channel
 *	Total Size: 1 * 247287 + 4 (header) = 247331 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\cs2261\M4\end.wav
 *	Time-stamp: Wed Apr 11 20:21:41 2018
 *	
 **************************************************************/

#ifndef __ENDH__
#define __ENDH__

#define ENDFREQ 11025
#define ENDLEN 247287

extern const unsigned char end[247287];

#endif /* __ENDH__ */
