
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 784564 bytes/channel
 *	Total Size: 1 * 784564 + 4 (header) = 784608 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\cs2261\M4\gameSong.wav
 *	Time-stamp: Wed Apr 11 19:53:58 2018
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 784564

extern const unsigned char gameSong[784564];

#endif /* __GAMESONGH__ */
