
/**************************************************************
 *	
 *	heart, 8 bit, 11025Hz,
 *	1 channel, 4210 bytes/channel
 *	Total Size: 1 * 4210 + 4 (header) = 4254 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\cs2261\M4\heart.wav
 *	Time-stamp: Wed Apr 11 21:27:16 2018
 *	
 **************************************************************/

#ifndef __HEARTH__
#define __HEARTH__

#define HEARTFREQ 11025
#define HEARTLEN 4210

extern const unsigned char heart[4210];

#endif /* __HEARTH__ */
