
/**************************************************************
 *	
 *	rupee, 8 bit, 11025Hz,
 *	1 channel, 3316 bytes/channel
 *	Total Size: 1 * 3316 + 4 (header) = 3360 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\cs2261\M4\rupee.wav
 *	Time-stamp: Wed Apr 11 21:14:23 2018
 *	
 **************************************************************/

#ifndef __RUPEEH__
#define __RUPEEH__

#define RUPEEFREQ 11025
#define RUPEELEN 3316

extern const unsigned char rupee[3316];

#endif /* __RUPEEH__ */
