
/**************************************************************
 *	
 *	rupeeSpecial, 8 bit, 11025Hz,
 *	1 channel, 4813 bytes/channel
 *	Total Size: 1 * 4813 + 4 (header) = 4857 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\cs2261\M4\rupeeSpecial.wav
 *	Time-stamp: Wed Apr 11 21:14:26 2018
 *	
 **************************************************************/

#ifndef __RUPEESPECIALH__
#define __RUPEESPECIALH__

#define RUPEESPECIALFREQ 11025
#define RUPEESPECIALLEN 4813

extern const unsigned char rupeeSpecial[4813];

#endif /* __RUPEESPECIALH__ */
