
/**************************************************************
 *	
 *	thud, 8 bit, 11025Hz,
 *	1 channel, 4301 bytes/channel
 *	Total Size: 1 * 4301 + 4 (header) = 4345 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\cs2261\M4\thud.wav
 *	Time-stamp: Wed Apr 11 21:06:31 2018
 *	
 **************************************************************/

#ifndef __THUDH__
#define __THUDH__

#define THUDFREQ 11025
#define THUDLEN 4301

extern const unsigned char thud[4301];

#endif /* __THUDH__ */
