
/**************************************************************
 *	
 *	title, 8 bit, 11025Hz,
 *	1 channel, 245964 bytes/channel
 *	Total Size: 1 * 245964 + 4 (header) = 246008 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\cs2261\M4\title.wav
 *	Time-stamp: Wed Apr 11 20:22:58 2018
 *	
 **************************************************************/

#ifndef __TITLEH__
#define __TITLEH__

#define TITLEFREQ 11025
#define TITLELEN 245964

extern const unsigned char title[245964];

#endif /* __TITLEH__ */
